[package]
name = "geo-booleanop"
version = "0.1.0"
authors = ["Bodo Junglas <junglas@objectcode.de>"]

[dependencies]
geo = "0.10.2"
num-traits = "0.2"
geojson = "0.12.0"

[dev-dependencies]
rand = "0.3"

